# Generated by Django 4.1.7 on 2023-07-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
